### ISSUE TITLE
how can i change deploy setting to deploy on vercel?

### ISSUE THREAD

**Issue by michael860520** [olegdon/nuxt3-pnpm-monorepo#136]
I have the same settings as you and connected to the Vercel dashboard, but I'm encountering a build error after deploying my code. 
Do you have any suggestions on how I can resolve this issue?

- first time deploy error:
![CleanShot 2024-10-23 at 18 41 35@2x](https://github.com/user-attachments/assets/3706681e-459f-4e93-ac0b-e66671b4002c)

- deploy setting:

![CleanShot 2024-10-23 at 18 42 31@2x](https://github.com/user-attachments/assets/8bb0148d-190c-46b0-aadb-9648dc9b2ad0)

- my repo: https://github.com/michael860520/FE-workspace-monoRepo

**Comment by olegdon** [comment]
Hey 👋,

what do you have here? 
<img width="924" alt="image" src="https://github.com/user-attachments/assets/87eb6df6-435e-4c39-9333-6fed8bf6d1b5">

I have Nuxt as a selected Framework preset

**Comment by olegdon** [comment]
Since there is no response I count it as fixed

**Comment by michael860520** [comment]
yes, it will work, thanks for you supprot
